sflx <- function() {
	# DETERMINE IF IT'S PRECIPITATING AND WHAT KIND OF PRECIP IT IS.
	# IF IT'S RAINING AND THE AIR TEMP IS COLDER THAN 0 C, IT'S SNOWING!
	# IF IT'S RAINING AND THE AIR TEMP IS WARMER THAN 0 C, BUT THE GRND
	# TEMP IS COLDER THAN 0 C, FREEZING RAIN IS PRESUMED TO BE FALLING.
	if (rain > 0) {
		if (air <= FRZ) {
			stop("snowing") # SNOWNG <- TRUE
		}else{
			if (TSKIN <= FRZ) stop("freezing rain") # FRZGRA <- TRUE
		}
	}

	# PRECIP IS LIQUID (RAIN), HENCE SAVE IN THE PRECIP VARIABLE THAT
	# LATER CAN WHOLELY OR PARTIALLY INFILTRATE THE SOIL
	RAIN1 = rain

	# CALCULATE THE SUBSURFACE HEAT FLUX, WHICH FIRST REQUIRES
	# CALCULATION OF THE THERMAL DIFFUSIVITY.
	# ------------------------------------------------------------- #
	# in this model the thermal difusivity is assumed that of the animal
	DF1 = BODY_DIFUSIVITY

	# CALCULATE SUBSURFACE HEAT FLUX, SSOIL, FROM FINAL THERMAL DIFFUSIVITY
	# OF SURFACE MEDIUMS, DF1 ABOVE, AND SKIN TEMPERATURE AND TOP
	# MID-LAYER SOIL TEMPERATURE
	SSOIL = DF1 * (TSKIN - STC[1]) / -(0.5 * ZSOIL[1])


	# NEXT CALL ROUTINE SFCDIF TO CALCULATE THE SFC EXCHANGE COEF (CH) FOR
	# HEAT AND MOISTURE.

	# NOTE !!!
	# ROUTINE SFCDIF RETURNS A CH THAT REPRESENTS THE WIND SPD TIMES THE
	# "ORIGINAL" NONDIMENSIONAL "Ch" TYPICAL IN LITERATURE.  HENCE THE CH
	# RETURNED FROM SFCDIF HAS UNITS OF M/S.  THE IMPORTANT COMPANION
	# COEFFICIENT OF CH, CARRIED HERE AS "RCH", IS THE CH FROM SFCDIF TIMES
	# AIR DENSITY AND PARAMETER "CP".  "RCH" IS COMPUTED IN "CALL PENMAN".
	# RCH RATHER THAN CH IS THE COEFF USUALLY INVOKED LATER IN EQNS.

	# NOTE !!!
	# SFCDIF ALSO RETURNS THE SURFACE EXCHANGE COEFFICIENT FOR MOMENTUM, CM,
	# ALSO KNOWN AS THE SURFACE DRAGE COEFFICIENT, BUT CM IS NOT USED HERE.
	# ------------------------------------------------------------- #
	# CALC VIRTUAL TEMPS AND VIRTUAL POTENTIAL TEMPS NEEDED BY SUBROUTINES
	# SFCDIF AND PENMAN.
	# ------------------------------------------------------------- #
	T2V  =   air * (1 + 0.61 * Q2)
	T1V  = TSKIN * (1 + 0.61 * Q2)
	TH2V = TH2   * (1 + 0.61 * Q2)
	flush.vars(environment())
	SFCDIF()

	# PREPARE PARTIAL QUANTITIES FOR PENMAN EQUATION
	DELTA = ELCP * DQSDT
	T24   = air^4
	RR    = T24 * 6.48e-8 / (pres * CH) + 1
	RHO   = pres / (R * T2V)
	RCH   = RHO * CP * CH

	# ADJUST THE PARTIAL SUMS / PRODUCTS WITH THE LATENT HEAT
	# EFFECTS CAUSED BY FALLING PRECIPITATION
	if (rain > 0) RR = RR + CW * rain / RCH
	FNET = FDOWN - SIGMA * T24 * EMISSIVITY - SSOIL

	# FINISH PENMAN EQUATION CALCULATIONS
	RAD   = FNET / RCH + TH2 - air
	A     = ELCP * (Q2SAT - Q2)
	EPSCA = (A * RR + RAD * DELTA) / (DELTA + RR)
	ETP   = EPSCA * RCH / LVH2O
	#---------------------#

	# CALCULATE SOIL HEAT FLUX VALUES AND UPDATE SOIL HEAT CONTENT
	flush.vars(environment())
	NOPAC()

	EDIR = EDIR * LVH2O
	ET[1:4] = ET[1:4] * LVH2O
	ETP   = ETP * LVH2O
	if (ETP > 0) {
		ETA = EDIR
	}else{
		ETA = ETP
	}
	BETA  = ETA / ETP

	# CONVERT THE SIGN OF SOIL HEAT FLUX SO THAT:
	#   SSOIL>0: WARM THE SURFACE  (NIGHT TIME)
	#   SSOIL<0: COOL THE SURFACE  (DAY TIME)
	SSOIL = -SSOIL

	# return
	check.vars(environment())
	flush.vars(environment())
}
